# Configurable facility-response vocabulary.
# Specific negative/pending phrases are evaluated before positive phrases.

CONFIRMED_PHRASES = [
    "approved and confirmed",
    "approved for the shift",
    "confirmed for the shift",
    "accepted for the shift",
    "approved to work",
    "confirmed to work",
    "accepted to work",
    "has been approved",
    "has been confirmed",
    "has been accepted",
    "have been approved",
    "have been confirmed",
    "have been accepted",
    "we approve",
    "we confirm",
    "we accept",
    "facility approves",
    "facility confirms",
    "facility accepts",
    "okay to proceed",
    "ok to proceed",
    "please proceed",
    "proceed with",
    "move forward with",
    "move forward",
    "good to go",
    "all set",
    "locked in",
    "greenlit",
    "green light",
    "finalized",
    "finalised",
    "approved",
    "confirmed",
    "accepted",
    "logged",
    "booked",
    "cleared",
    "selected",
    "chosen",
    "assigned",
    "scheduled",
    "rostered",
    "placed",
    "proceed",
    "can use this clinician",
    "please schedule",
    "please book",
    "works for us",
    "approved candidate",
    "confirmed candidate",
    "accepted candidate",
    "candidate approved",
    "candidate confirmed",
    "candidate accepted",
]

REJECTED_PHRASES = [
    "not approved",
    "not confirmed",
    "not accepted",
    "not selected",
    "not chosen",
    "not cleared",
    "do not proceed",
    "don't proceed",
    "cannot approve",
    "can't approve",
    "unable to approve",
    "cannot confirm",
    "unable to confirm",
    "cannot accept",
    "unable to accept",
    "no longer needed",
    "declined",
    "rejected",
    "cancelled",
    "canceled",
    "cancel this submission",
    "please withdraw",
    "do not schedule",
    "do not book",
]

PENDING_PHRASES = [
    "pending approval",
    "pending confirmation",
    "pending decision",
    "decision pending",
    "under review",
    "being reviewed",
    "still reviewing",
    "awaiting approval",
    "awaiting confirmation",
    "awaiting decision",
    "on hold",
    "please hold",
    "will confirm",
    "will update",
    "need more time",
    "not yet confirmed",
    "not yet approved",
    "not yet accepted",
]

PHRASE_GROUPS = [
    ("REJECTED", REJECTED_PHRASES),
    ("PENDING", PENDING_PHRASES),
    ("CONFIRMED", CONFIRMED_PHRASES),
]
